import { randomUUID } from "node:crypto";
import type {
  BusinessContext,
  CommunicationStrategy,
  CopywriterOutput,
  SemanticTemplateModel,
  StrategyPlan,
  TemplateComponent,
  TemplateVariable,
} from "../types/index.js";
import type {
  MessageRealizationResult,
} from "../core/realization-engine.js";
import {
  CopyBlockKind,
  CopyBlockVariantRole,
  type CopyBlock,
  type CopyBlockSet,
} from "../core/copy-block.model.js";
import { MessageSectionType, type MessageStructure } from "../core/message-structure.model.js";
import { OpenAiJsonClient, PipelineLogger, PromptRegistry } from "../ai/index.js";
import { validateSemanticTemplate } from "../core/semantic-template.validation.js";

interface OperationalCopywriterInput {
  businessContext: BusinessContext;
  communicationStrategy: CommunicationStrategy;
  semanticTemplateModel: SemanticTemplateModel;
  baseline: MessageRealizationResult;
}

interface OperationalCopywriterResult extends MessageRealizationResult {
  copyNotes: string;
  alternatives: TemplateComponent[][];
  aiWarnings: string[];
}

interface CopywriterAiOutput {
  components?: TemplateComponent[];
  alternatives?: TemplateComponent[][];
  copyNotes?: string;
  humanizedVersions?: string[];
  warnings?: string[];
}

export class CopywriterAgent {
  private readonly ai = new OpenAiJsonClient();
  private readonly logger = new PipelineLogger();

  async run(input: { strategy: StrategyPlan; businessContextId: string }): Promise<CopywriterOutput> {
    const components = input.strategy.semanticModel
      ? createLegacyComponents(input.strategy)
      : [];

    return {
      components,
      variablesUsed: input.strategy.suggestedVariables,
      semanticModel: input.strategy.semanticModel,
      copyNotes: "Legacy /api copywriter generated deterministic components.",
      alternatives: components.length > 0 ? [components] : [],
    };
  }

  async writeDraft(input: OperationalCopywriterInput): Promise<OperationalCopywriterResult> {
    const aiResult = await this.ai.completeJson<CopywriterAiOutput>({
      agent: "CopywriterAgent",
      systemPrompt: PromptRegistry.copywriter,
      fallbackLabel: "RealizationEngine output",
      userPayload: {
        businessContext: input.businessContext,
        communicationStrategy: input.communicationStrategy,
        semanticTemplate: input.semanticTemplateModel,
        variableBindings: input.semanticTemplateModel.variableBindings,
        baselineComponents: input.baseline.templateComponents.components,
        requiredJsonShape: {
          components: [
            { type: "BODY", text: "string with {{1}} tokens", example: { body_text: [["example"]] } },
          ],
          alternatives: [[{ type: "BODY", text: "alternative" }]],
          copyNotes: "string",
          warnings: ["string"],
        },
      },
    });

    const normalized = aiResult.output?.components
      ? normalizeComponents(aiResult.output.components, input.baseline)
      : null;
    const validation = normalized
      ? validateSemanticTemplate({
          name: "copywriter_ai_output",
          category: input.communicationStrategy.recommendedCategory,
          components: normalized,
        })
      : { valid: false };

    const components = normalized && validation.valid
      ? normalized
      : input.baseline.templateComponents.components;
    const warnings = [
      ...input.baseline.warnings,
      ...aiResult.warnings,
      ...(aiResult.output?.warnings ?? []),
      ...(normalized && !validation.valid ? ["CopywriterAgent AI output failed structural validation; baseline components were used."] : []),
    ];
    const copyBlocks = createCopyBlocksFromComponents(components, input.baseline.messageStructure);

    this.logger.info({
      agent: "CopywriterAgent",
      stage: "copy.completed",
      detail: {
        aiSkipped: aiResult.skipped,
        usedAiComponents: Boolean(normalized && validation.valid),
        componentCount: components.length,
        warnings,
      },
    });

    return {
      messageStructure: input.baseline.messageStructure,
      copyBlocks,
      templateComponents: {
        components,
        warnings,
      },
      warnings,
      copyNotes: aiResult.output?.copyNotes ?? "Copy generated by deterministic realization fallback.",
      alternatives: normalizeAlternatives(aiResult.output?.alternatives, input.baseline.templateComponents.components),
      aiWarnings: aiResult.warnings,
    };
  }
}

function createLegacyComponents(strategy: StrategyPlan): TemplateComponent[] {
  const bodyText = [
    `Ola {{1}}, ${strategy.messagingGoal}`,
    strategy.callToAction ? `${strategy.callToAction}.` : "Responda para continuar.",
  ].join(" ");

  return [{
    type: "BODY",
    text: bodyText.slice(0, 1024),
    example: {
      body_text: [[strategy.suggestedVariables[0]?.example ?? "Ana"]],
    },
  }];
}

function normalizeComponents(
  components: TemplateComponent[],
  baseline: MessageRealizationResult
): TemplateComponent[] {
  const expectedExamples = baseline.messageStructure.variablePlaceholders.map((variable) => variable.example);
  const safe = components.slice(0, 4).map((component) => {
    if (component.type === "HEADER") {
      return { ...component, text: component.text?.slice(0, 60) };
    }
    if (component.type === "BODY") {
      const text = normalizeVariableTokens(component.text).slice(0, 1024);
      const variableCount = countVariables(text);
      return {
        ...component,
        text,
        example: variableCount > 0
          ? { body_text: [expectedExamples.slice(0, variableCount).length ? expectedExamples.slice(0, variableCount) : ["Ana"]] }
          : undefined,
      };
    }
    if (component.type === "FOOTER") {
      return { ...component, text: component.text.slice(0, 60) };
    }
    return {
      ...component,
      buttons: component.buttons.slice(0, 3).map((button) => (
        "text" in button ? { ...button, text: button.text.slice(0, 25) } : button
      )),
    };
  });

  return safe.some((component) => component.type === "BODY")
    ? safe
    : baseline.templateComponents.components;
}

function normalizeAlternatives(
  alternatives: TemplateComponent[][] | undefined,
  fallback: TemplateComponent[]
): TemplateComponent[][] {
  if (!alternatives?.length) return [fallback];
  return alternatives.slice(0, 3);
}

function createCopyBlocksFromComponents(
  components: TemplateComponent[],
  messageStructure: MessageStructure
): CopyBlockSet {
  const blocks: CopyBlock[] = [];
  const header = components.find((component) => component.type === "HEADER");
  const body = components.find((component) => component.type === "BODY");
  const footer = components.find((component) => component.type === "FOOTER");
  const buttons = components.find((component) => component.type === "BUTTONS");

  if (header?.type === "HEADER" && header.text) {
    blocks.push(createBlock(CopyBlockKind.Header, MessageSectionType.Opening, header.text));
  }
  if (body?.type === "BODY") {
    blocks.push(createBlock(CopyBlockKind.BodyMain, MessageSectionType.MainMessage, body.text));
  }
  if (footer?.type === "FOOTER") {
    blocks.push(createBlock(CopyBlockKind.Footer, MessageSectionType.Footer, footer.text));
  }
  if (buttons?.type === "BUTTONS") {
    for (const button of buttons.buttons) {
      blocks.push(createBlock(
        CopyBlockKind.Button,
        MessageSectionType.ButtonSet,
        "text" in button ? button.text : button.example,
      ));
    }
  }

  return {
    id: randomUUID(),
    blocks,
    warnings: messageStructure.warnings,
  };
}

function createBlock(kind: CopyBlockKind, sectionType: MessageSectionType, text: string): CopyBlock {
  return {
    id: randomUUID(),
    kind,
    sectionType,
    variantRole: CopyBlockVariantRole.Primary,
    text,
    variables: [...new Set([...text.matchAll(/\{\{(\d+)\}\}/g)].map((match) => `{{${match[1]}}}`))],
    rationale: "Generated by CopywriterAgent.",
    warnings: [],
  };
}

function normalizeVariableTokens(text: string): string {
  const found = [...new Set([...text.matchAll(/\{\{(\d+)\}\}/g)].map((match) => match[0]))];
  let normalized = text;
  for (const [index, token] of found.entries()) {
    normalized = normalized.replaceAll(token, `{{${index + 1}}}`);
  }
  return normalized;
}

function countVariables(text: string): number {
  return new Set([...text.matchAll(/\{\{(\d+)\}\}/g)].map((match) => match[1])).size;
}
